apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: wordpress
  name: wordpress
spec:
  host: wordpress-wordpress-sql.apps.demo.idmdte.net
  port:
    targetPort: 80
  to:
    kind: Service
    name: wordpress
    weight: 100
  wildcardPolicy: None