apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: guestbook-app
  namespace: lab14-liberty-operator
spec:
  replicas: 1
  applicationImage: 'lab13-jenkins/get-started-java:latest'
  serviceability:
    size: 1Gi
  expose: true
  env:
    - name: MONGO_URL
      valueFrom:
        secretKeyRef:
          name: mongo-url
          key: mongo-url